### ISSUE TITLE
[BUG] check_is_scitype throws an error when passed a valid pd.DataFrame formed through concatenation

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#3471]
**Describe the bug**

check_is_scitype does not work correctly when the pandas DataFrame storing X has been formed through pandas.concat operation. It raises a type error 

"X is not of a supported input data type.X must be in a supported mtype format for Panel, found <class 'pandas.core.frame.DataFrame'>"

this is a problem because we often load the train and test and merge them together. This error also occurs with resampling dataloaded from file, this is the cut down version

**To Reproduce**

```python
from sktime.utils._testing.panel import _make_panel_X
from sktime.classification.dummy import DummyClassifier
import numpy as np
import pandas as pd
trainX = _make_panel_X(n_instances=40)
trainY = np.random.randint(low=0,high=2,size=40)
dummy = DummyClassifier()
# this works
dummy.fit(trainX,trainY)
trainX2 = _make_panel_X(n_instances=40)
trainX2=pd.concat([trainX2,trainX])
trainY2 = np.random.randint(low=0,high=2,size=80)
# this throws a type error
dummy.fit(trainX2,trainY2)
```

**Expected behavior**
This code works with version 0.13.0 and lower, but throws the above error in 0.13.1. 
**Additional context**

**Versions**
<details>
![image](https://user-images.githubusercontent.com/9594042/191950092-33d72f76-898c-4c20-ad9e-acafb766ffdc.png)
</details>

**Comment by fkiraly** [comment]
Is this fixed by #3463?

**Comment by TonyBagnall** [comment]
I've just run the exact code above on main and still get the same type error

**Comment by fkiraly** [comment]
intended behaviour since `trainX2` does not conform with the `nested_univ` format specification - it has non-unique row index.

If the user follows the instructions to check the input, that appears as the error message.

If you would like a more descriptive error message, you can make a PR to add code like in `BaseForecaster._check_X_y`.
