### ISSUE TITLE
[BUG] The name for the timepoints index level is not included after prediction.

### ISSUE THREAD

**Issue by kdekker-kdr4** [sktime/sktime#7671]
**Describe the bug**
The name for the timepoints index level is not included after prediction.
The other index names are, except for the timepoints.

**To Reproduce**

```python
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.forecasting.arima import ARIMA

y = _make_hierarchical()
forecaster = ARIMA()

y_pred = forecaster.fit(y, fh=[1, 2]).predict()
y_pred

expected_index_names =  ["h0","h1","time"]
assert y.index.names == expected_index_names 
assert y_pred.index.names== expected_index_names 
```

**Expected behavior**
The index names of predictions should represent the index names of the data learned on.

**Versions**
0.34.0

**Comment by fkiraly** [comment]
Quick question - is this true only for ARIMA, or all forecasters?

**Comment by PTUsumit** [comment]
Can I work on this issue.

**Comment by PTUsumit** [comment]
I think this code will work as it given 

from sktime.forecasting.naive import NaiveForecaster
from sktime.datasets import load_airline


y = load_airline()


expected_index_names = ["time"]
y.index.names = expected_index_names
assert y.index.names == expected_index_names

# Instantiate and use the NaiveForecaster
forecaster = NaiveForecaster()

# Fit and predict
y_pred = forecaster.fit(y, fh=[1, 2]).predict()

# Manually fix the index names for the predictions
y_pred.index.names = expected_index_names

# Check that the index names are correctly set
assert y_pred.index.names == expected_index_names  # Should now pass

**Comment by kdekker-kdr4** [comment]
It is unclear to me if you are asking the user to add a line in their code.

```
y_pred.index.names = expected_index_names
```

This should happen under the hood.

**Comment by fkiraly** [comment]
FYI @ericjb, I think this might also be fixed by your fix?

It would be appreciated if you could check with the MRE provided here, whether your PR https://github.com/sktime/sktime/pull/7762 fixes this.

**Comment by ericjb** [comment]
PR #7762 does not fix this because it is unrelated in several ways.

1. PR #7762 affects the function convert_MvS_to_UvS_as_Series in datatypes/_series/_convert.py. It modifies that function so that the column name of the input DataFrame becomes the Series name for the returned Series. This PR is not concerned about the column name or the Series name. It is concerned about the index name.
2. convert_MvS_to_UvS_as_Series  returns a Series with the same index name as its input DataFrame
3. convert_MvS_to_UvS_as_Series  deals (typically) with the inputs to the fit method. This PR deals with the outputs of the predict method.
